from __future__ import annotations

"""
CueBI — dbt Manifest Parser

Parses dbt's manifest.json into SchemaInfo objects the rest of the pipeline
already understands. manifest.json is generated by `dbt compile` or `dbt run`
in the target/ directory and is the single source of truth for your dbt project.

What we extract:
  - Model names, descriptions, target Redshift schema/database
  - Column names, descriptions, data types
  - Primary keys  — inferred from `unique` tests
  - Foreign keys  — inferred from `relationships` tests
  - Lineage       — parent model names from parent_map
"""

import re
from typing import Optional

from packages.connectors.base import SchemaInfo, TableInfo, ColumnInfo


def parse_manifest(manifest_data: dict) -> SchemaInfo:
    """
    Parse a dbt manifest.json dict into a SchemaInfo.

    Args:
        manifest_data: Parsed JSON dict from manifest.json

    Returns:
        SchemaInfo with tables/columns populated from dbt models,
        descriptions from YAML docs, PKs/FKs from test metadata.
    """
    nodes = manifest_data.get("nodes", {})
    parent_map = manifest_data.get("parent_map", {})

    # ── Pass 1: Collect test metadata per model ──────────────────────────────
    # Map: node_unique_id → { col_name → {is_pk, fk_model, fk_field} }
    column_tests: dict[str, dict[str, dict]] = {}

    for node_id, node in nodes.items():
        if not node_id.startswith("test."):
            continue

        test_meta = node.get("test_metadata", {})
        test_name = test_meta.get("name", "")
        kwargs = test_meta.get("kwargs", {})
        attached = node.get("attached_node", "")

        if not attached or not test_name:
            continue

        col_name = kwargs.get("column_name", "")
        if not col_name:
            continue

        if attached not in column_tests:
            column_tests[attached] = {}
        if col_name not in column_tests[attached]:
            column_tests[attached][col_name] = {}

        if test_name == "unique":
            column_tests[attached][col_name]["is_pk"] = True

        elif test_name == "relationships":
            to_model = _extract_ref_name(kwargs.get("to", ""))
            to_field = kwargs.get("field", "id")
            if to_model:
                column_tests[attached][col_name]["fk_model"] = to_model
                column_tests[attached][col_name]["fk_field"] = to_field

    # ── Pass 2: Build TableInfo for each model node ──────────────────────────
    tables: list[TableInfo] = []
    inferred_database = ""

    for node_id, node in nodes.items():
        if not node_id.startswith("model."):
            continue
        if node.get("resource_type") != "model":
            continue

        model_name = node.get("name", "")
        if not model_name:
            continue

        config = node.get("config", {})
        dbt_schema = config.get("schema") or node.get("schema", "") or ""
        dbt_database = config.get("database") or node.get("database", "") or ""

        if dbt_database and not inferred_database:
            inferred_database = dbt_database

        # Lineage: direct model parents only (skip sources/seeds)
        parents = parent_map.get(node_id, [])
        parent_names = [p.split(".")[-1] for p in parents if p.startswith("model.")]

        # Columns
        raw_cols = node.get("columns", {})
        node_col_tests = column_tests.get(node_id, {})

        columns: list[ColumnInfo] = []
        for col_name, col_data in raw_cols.items():
            ct = node_col_tests.get(col_name, {})
            fk_model = ct.get("fk_model")
            fk_field = ct.get("fk_field")

            columns.append(ColumnInfo(
                name=col_name,
                data_type=col_data.get("data_type") or "unknown",
                is_nullable=True,
                is_primary_key=ct.get("is_pk", False),
                is_foreign_key=bool(fk_model),
                references_table=fk_model,
                references_column=fk_field,
                description=col_data.get("description") or "",
                sample_values=[],
            ))

        tables.append(TableInfo(
            name=model_name,
            columns=columns,
            row_count=None,
            description=node.get("description") or "",
            dbt_schema=dbt_schema,
            dbt_database=dbt_database,
            lineage=parent_names,
        ))

    return SchemaInfo(
        tables=tables,
        dialect="redshift",
        database_name=inferred_database or "redshift",
    )


def get_manifest_stats(manifest_data: dict) -> dict:
    """Return summary counts for the upload response."""
    nodes = manifest_data.get("nodes", {})

    model_count = 0
    test_count = 0
    total_cols = 0
    documented_cols = 0

    for node_id, node in nodes.items():
        if node_id.startswith("test."):
            test_count += 1
        elif node_id.startswith("model.") and node.get("resource_type") == "model":
            model_count += 1
            for col_data in node.get("columns", {}).values():
                total_cols += 1
                if col_data.get("description"):
                    documented_cols += 1

    return {
        "model_count": model_count,
        "test_count": test_count,
        "column_count": total_cols,
        "documented_column_count": documented_cols,
    }


def _extract_ref_name(ref_str: str) -> Optional[str]:
    """Extract model name from a ref('model_name') string."""
    if not ref_str:
        return None
    match = re.search(r"ref\(['\"]([^'\"]+)['\"]\)", ref_str)
    return match.group(1) if match else None
